name: Fetch deb
description: Fetch deb package from release
inputs:
  owner:
    description: "Repository owner"
    required: false
    default: golemfactory
  repo:
    description: "Repository name"
    required: true
  pattern:
    description: "Version pattern"
    required: true
  out-dir:
    description: "Output directory"
    required: false
    default: packages
  prerelease:
    description: "Should look for prelease or full release only"
    required: false
    # If not specified both prerelease and full release are considered

runs:
  using: composite
  steps:
    - name: "Get release"
      id: get_release
      # Previously used joutvhu/get-release action, but it doesn't handle pagination
      # when querying releases. This is workaround and has its downsides.
      uses: cardinalby/git-get-release-action@1.2.4
      with:
        repo: ${{ inputs.owner }}/${{ inputs.repo }}
        # Checks release name not a tag, but tag doesn't support regex.
        # It introduces the assumption that tag is part of the name!
        releaseNameRegEx: ${{ inputs.pattern }}
        prerelease: ${{ inputs.prerelease }}
    - name: "Fetch deb package: yagna"
      uses: robinraju/release-downloader@v1.10
      with:
        repository: ${{ inputs.owner }}/${{ inputs.repo }}
        tag: ${{ steps.get_release.outputs.tag_name }}
        fileName: "*.deb"
        out-file-path: ${{ inputs.out-dir }}
        tarBall: false
        zipBall: false
